### ISSUE TITLE
Different templatemap_generator symlink during composer install

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-view#17] opened 2019-12-31 22:36 UTC
Sometimes, when I run composer install, it create in the folder `vendor/bin` a symlink `templatemap_generator.php` that links to `../zendframework/zendframework/bin/templatemap_generator.php`

Sometimes, that file links to `./zendframework/zendframework/bin/pluginmap_generator.php`

What's the criteria and how to force to choose the last one (that I think it's the newest one)?

---

Originally posted by @pensiero at https://github.com/zendframework/zend-view/issues/86

**Comment by samsonasik** [comment] 2020-07-16 01:01
I can't reproduce in the latest `laminas-mvc-skeleton`. Please re-create issue if the problem persist.

I'm closing it

**Closed by samsonasik** 2020-07-16 01:01 UTC
